### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mbs-code** [mbs-code/task-diary#1]
## Bug Fix

- [x] fix データ読み込み時、最上位まで読みに行ってしまう問題
  - 再読み込み時、1要素ごとに focus 処理が走っているせい
  - ロード時と更新時で処理を分ける

## 優先度高め

- [x] paneダブルクリックで拡縮
- [ ] TODO ペインを TODO とわかりやすくする
- [x] color pallet を実装
- [x] card に 時間を表示（n秒前）
  - そのカードに表示するかは切り替える
- [x] 再読み込みボタン、本日へのボタン
- [ ] 一行目を強調表示、色付け
- [x] 新規作成ボタンをインラインで操作可能なようにする
  - 視線の都合、ダイアログはうっとおしい
- [x] トースト実装
  - get はサイレント、その他はmessageを出す 

## 優先度低め

- [ ] その場で案件を作るモード
  - 簡易編集に案件ダイアログ表示ボタン
  - データ更新をどうするか
- [ ] report API を改造して relation で取ってくるのを辞める
  - 直接 projectService の保持値を参照する
  - するとリアクティブになる
- [ ] TL スマートフォン表示
  - 画面幅が狭いときに card だけの表記にする
- [ ] 日付検索実装
  - 日付表記を押したらカレンダー -> その日に移動
- [ ]  ダミーデータのクオリティを上げる
  - how to も混ぜる

## 荒目のタスク

- [ ] status 実装
- [ ] 案件検索機能
  - 案件で抽出して表示する
- [ ] テキスト検索機能
- [ ] 設定画面
- [ ] ショートカットキー
- [ ] 一定時間おきに通知、更新忘れてないかの確認
- [x] 日時ピッカーが使いにくいので検討
- [ ] ドロップでTODOへ移動

**Comment by mbs-code** [comment]
- [x] project 編集テーブルが壊れてる
- [x] スクロール読み込みが壊れてる

**Comment by mbs-code** [comment]
- [ ] projectの順番を使った順にする
  - last_used_at カラムを作成
  - reportで保存したタイミングで、更新

**Comment by mbs-code** [comment]
- [ ] scrollIntoView の composable 化
- [ ] 英語対応
- [ ] TODOのドロワー機能
- [ ] 時間パネルの共通サービス化

**Comment by mbs-code** [comment]
アプデ記録
![image](https://user-images.githubusercontent.com/46484466/202834436-c5d9fe6f-5e35-4c3c-a9d6-b4d35a14d00a.png)
